### ISSUE TITLE
failure building flang with clang 6.0: "non-constant-expression cannot be narrowed"

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#588]
Building the current flang master (at 932f7a3da7abf0535bbb23bde7d6cc6b84e73816) with clang 6.0.1 gives me the following error:

```
/home/janus/llvm6/flang/tools/flang2/flang2exe/iliutil.cpp:2096:50: error: non-constant-expression cannot be narrowed from type
      'unsigned int' to 'int32_t' (aka 'int') in initializer list [-Wc++11-narrowing]
    INT64 one_64 = {0x0, 0x1}, divisor64 = {0x0, udiv};
                                                 ^~~~
/home/janus/llvm6/flang/tools/flang2/flang2exe/iliutil.cpp:2096:50: note: insert an explicit cast to silence this issue
    INT64 one_64 = {0x0, 0x1}, divisor64 = {0x0, udiv};
                                                 ^~~~
                                                 static_cast<int32_t>( )
```

This must have been introduced recently. Using gcc 7.3 seems to work well, though.

**Comment by janusw** [comment]
@gklimowicz A quick bisection reveals that this regression was introduced in 23213ad759e2cb5f05798cb35d3e354564f9d649.

**Comment by janusw** [comment]
The issue is fixed by ed74454a0889ca5ffd3a99d05d82fd206ae98f26. Thanks!
