### ISSUE TITLE
fd_sincos_scalar.cpp: "error: ‘__builtin_complex’ was not declared in this scope"

### ISSUE THREAD

**Issue by bcfriesen** [flang-compiler/flang#602]
Hi,

commit f5376c0 ("Improve single/double precision sincos, double precision power") breaks the build on `fd_sincos_scalar.cpp` with this error message:
```
In file included from /usr/include/c++/7/complex.h:36:0,
                 from /home/friesen/flang/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp:41:
/home/friesen/flang/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp: In function ‘__complex__ double __fd_sincos_1_avx2(double)’:
/home/friesen/flang/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp:183:12: error: ‘__builtin_complex’ was not declared in this scope
     return CMPLX(rs, rc);
            ^
/home/friesen/flang/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp:183:12: note: suggested alternative: ‘__builtin_toupper’
```

This was with GCC 7.3.1 on SUSE, using `llvm` commit `e759b6cedf4` and `flang-driver` commit `f90d905b99`.

Reverting this commit fixes the error.

**Comment by bcfriesen** [comment]
I noticed that this commit works if I compile `libpgmath` with clang/clang++/flang rather than GCC. Is this the preferred build procedure? It was not clear from the build instructions whether flang needs to be bootstrapped or if it can be built entirely with GCC.

**Comment by d-parks** [comment]
Clang is the preferred compiler to build libpgmath.

What version of SUSE are you using?

**Comment by bcfriesen** [comment]
Hi David,

it's openSUSE Leap 42.3.

Thanks.

**Comment by d-parks** [comment]
Hi Brian,

Much appreciated.  BTW, my testing on OpenSUSE 42.3 shows a compile failure long before what you're reporting. Though I'm using gcc 7.3.0. Argh.

**Comment by d-parks** [comment]
Hi Brian,

Thanks for the suggestion.  I see that including <cmath> instead of <math.h> does work on SUSE. I'm currently testing to see whether <cmath> fix works for RHEL/OSX/...

Best regards,

Dave

**Comment by janusw** [comment]
I see the same problem on Ubuntu 18.04 (using gcc 7.3.0) ...

> I see that including `<cmath>` instead of `<math.h>` does work on SUSE. I'm currently testing to see whether `<cmath>` fix works for RHEL/OSX/...

... however this does not work for me:
```
diff --git a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
index d40be2c..c9c45c3 100644
--- a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
+++ b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
@@ -19,7 +19,7 @@
 
 #include <assert.h>
 #include <stdio.h>
-#include <math.h>
+#include <cmath>
 #if     defined(__x86_64__)
 #include <immintrin.h>
 #56 
```

**Comment by rofirrim** [comment]
Hi,

I also hit this issue and what worked for me using GCC 8.2.0 was replacing `complex.h` with `ccomplex`. I couldn't test it with earlier versions of GCC so YMMV here.

```diff
diff --git a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
index d40be2c..012d754 100644
--- a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
+++ b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
@@ -38,7 +38,7 @@
 #define S(...) __VA_ARGS__
 #define C(...) __VA_ARGS__
 #define FNAME   sincos
-#include <complex.h>
+#include <ccomplex>
 #undef  SINCOS_COMMA
 #define SINCOS_COMMA    ,
 #else
```

Hope it helps.

Kind regards.

**Comment by rofirrim** [comment]
> I also hit this issue and what worked for me using GCC 8.2.0 was replacing `complex.h` with `ccomplex`. I couldn't test it with earlier versions of GCC so YMMV here.

Oh nevermind, building from scratch will cause a failure in several other headers.

Sorry for the fuss.

**Comment by janusw** [comment]
> I also hit this issue and what worked for me using GCC 8.2.0 was replacing `complex.h` with `ccomplex`. I couldn't test it with earlier versions of GCC so YMMV here.
> 
> ```diff
> diff --git a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
> index d40be2c..012d754 100644
> --- a/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
> +++ b/runtime/libpgmath/lib/common/sincos/fd_sincos_scalar.cpp
> @@ -38,7 +38,7 @@
>  #define S(...) __VA_ARGS__
>  #define C(...) __VA_ARGS__
>  #define FNAME   sincos
> -#include <complex.h>
> +#include <ccomplex>
>  #undef  SINCOS_COMMA
>  #define SINCOS_COMMA    ,
>  #else
> ```

I can confirm that this fixes the issue (using gcc 8.3 here).

**Comment by keidavis** [comment]
Just ran into this myself, was lucky that Google hit this page.   Same error regarding CMPLX with both gcc 7.3.0 and gcc 8.2.0.  Used 

    -DCMAKE_CXX_COMPILER=$INSTALL_PREFIX/bin/clang++ \
    -DCMAKE_C_COMPILER=$INSTALL_PREFIX/bin/clang \

from the instructions here (step 5)

  https://github.com/flang-compiler/flang/wiki/Building-Flang

to bootstrap using the just-built Flang clang++.  Noted that parallel build (make -j) does not work--complains of empty files.  Now we'll see if it actually runs or if a complete bootstrap is needed.  Also noted that setup.sh breaks step 2 because the C/C++ compiler specified doesn't exist yet.

**Comment by janusw** [comment]
The problem seems to be gone on current master. I think it was fixed with 7fcd6346a9427977afe4534c0f19bbbba04c99a3. The issue can be closed.

**Comment by gklimowicz** [comment]
Thanks for the confirmation, Janus.
