### ISSUE TITLE
libpgmath: build failures with glibc 2.27

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#545]
After the previous problems in #434 had finally disappeared, new build problems in libpgmath have been introduced recently. At 1c2d85e2d488ed23c4f6be05729fd0a9b6b4ed2d, I can not build libpgmath at all, neither with clang 6 nor with gcc 7.

clang complains:
```
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/dlog.c:59:20: error: variable has incomplete type 'struct exception'
  struct exception exc;
                   ^
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/dlog.c:59:10: note: forward declaration of 'struct exception'
  struct exception exc;
         ^
```

while gcc says:
```
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/dlog.c: In function ‘retval_errno_erange_overflow’:
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/dlog.c:59:20: error: storage size of ‘exc’ isn’t known
   struct exception exc;
                    ^~~
```

**Comment by bcfriesen** [comment]
I see this error as well. With Ubuntu + GCC:
```
friesen@0ab3f78083ac:~/src/flang/runtime/libpgmath/build$ cc --version
cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
```
On commit 1c2d85e it encounters these errors:
```
[ 64%] Building C object lib/x86_64/CMakeFiles/avx2_log10.dir/dlog.c.o
cd /home/friesen/src/flang/runtime/libpgmath/build/lib/x86_64 && /usr/bin/cc -DCOMPILING_LOG10 -DFN_PROTO_SUFFIX=_avx2 -DHOST_LINUX -DLINUX -DLINUX86 -DLINUX8664 -DMAXCPUS=256 -DMAXCPUSL=8 -DMAXCPUSR=8 -DPG_PIC -DTARGET_LINUX -DTARGET_LINUX_X86 -DTARGET_LINUX_X8664 -DTARGET_X86 -DTARGET_X8664 -D_GNU_SOURCE -D_ISOC99_SOURCE -D__gnu_linux__ -I/home/friesen/src/flang/runtime/libpgmath/lib/common -I/home/friesen/src/flang/runtime/libpgmath/lib/x86_64  -O3 -DNDEBUG -fPIC   -m64 -O3 -Wall -W -Wstrict-prototypes -Wwrite-strings -Werror  -mavx2 -mfma -ffp-contract=fast -o CMakeFiles/avx2_log10.dir/dlog.c.o   -c /home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c: In function 'retval_errno_erange_overflow':
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:59:20: error: storage size of 'exc' isn't known
   struct exception exc;
                    ^~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:62:14: error: 'SING' undeclared (first use in this function)
   exc.type = SING;
              ^~~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:62:14: note: each undeclared identifier is reported only once for each function it appears in
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:59:20: error: unused variable 'exc' [-Werror=unused-variable]
   struct exception exc;
                    ^~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c: In function 'retval_errno_edom':
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:78:20: error: storage size of 'exc' isn't known
   struct exception exc;
                    ^~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:81:14: error: 'DOMAIN' undeclared (first use in this function)
   exc.type = DOMAIN;
              ^~~~~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:78:20: error: unused variable 'exc' [-Werror=unused-variable]
   struct exception exc;
                    ^~~
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c: In function 'retval_errno_erange_overflow':
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:72:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c: In function 'retval_errno_edom':
/home/friesen/src/flang/runtime/libpgmath/lib/x86_64/dlog.c:91:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
```

**Comment by sscalpone** [comment]
As of GCC glibc 2.27,  math.h no longer defines struct exception.  The code in dlog.c and probably a few other files needs to have the exception handling removed; as far as I know, no Fortran code, and in the future, no C/C++ code, should depend on old-style exception handling.

**Comment by janusw** [comment]
Yes, I'm indeed building on a system with glibc 2.27 (Ubuntu 18.04). On Ubuntu 16.04, which has glibc 2.23, libpgmath builds fine.

**Comment by ibara** [comment]
This would be beneficial to OpenBSD as well, as we also don't have that struct.

**Comment by naromero77** [comment]
Is there a work around for this issue?

**Comment by ibara** [comment]
If you're in a real pinch, you can change
https://github.com/flang-compiler/flang/blob/master/runtime/libpgmath/lib/x86_64/libm_amd.h#L71
from
`#if !defined(TARGET_WIN)`
to
`#if defined(TARGET_WIN)`

If you then get errors about missing defines, you can add the defines from NetBSD math.h
http://bxr.su/NetBSD/include/math.h#199
Lines 199 through 202.

Note that this is a *workaround* (although this is exactly what I do for the OpenBSD/amd64 package). @sscalpone already articulated the proper solution.

**Comment by janusw** [comment]
Thanks for fixing! I can confirm that libpgmath builds well on Ubuntu 18.04 now ...
